[connections.dev]
account   = "${{ env.SF_ACCOUNT }}"
user      = "${{ env.SF_USERNAME }}"
role      = "${{ env.SF_ROLE }}"
warehouse = "${{ env.SF_WAREHOUSE }}"
database  = "${{ env.SF_DATABASE }}"
schema    = "${{ env.SF_SCHEMA }}"

authenticator    = "snowflake_jwt"
private_key_file = ".secrets/rsa_key.p8"
