[connections.dev]
account   = "$SF_ACCOUNT"
user      = "$SF_USERNAME"
role      = "$SF_ROLE"
warehouse = "$SF_WAREHOUSE"
database  = "$SF_DATABASE"
schema    = "$SF_SCHEMA"

authenticator    = "snowflake_jwt"
private_key_file = ".secrets/rsa_key.p8"
